// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIuO8liW8d8itUPfyy0VPWgLJXm8TOqfM',
    appId: '1:371597182967:web:693c9cc7cd1f2524e350f2',
    messagingSenderId: '371597182967',
    projectId: 'shophop-b4133',
    authDomain: 'shophop-b4133.firebaseapp.com',
    storageBucket: 'shophop-b4133.firebasestorage.app',
    measurementId: 'G-JM66RJN48Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDfK7bcqNfrlHYppmZwv_MTZMYr2J7_pY',
    appId: '1:371597182967:android:3453c45ab18ac672e350f2',
    messagingSenderId: '371597182967',
    projectId: 'shophop-b4133',
    storageBucket: 'shophop-b4133.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3xFHomP7j4wvzd8R-Z_d_VS0Xjy4kw90',
    appId: '1:371597182967:ios:cf47a0caaa59fcebe350f2',
    messagingSenderId: '371597182967',
    projectId: 'shophop-b4133',
    storageBucket: 'shophop-b4133.firebasestorage.app',
    iosBundleId: 'com.example.shopHopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3xFHomP7j4wvzd8R-Z_d_VS0Xjy4kw90',
    appId: '1:371597182967:ios:cf47a0caaa59fcebe350f2',
    messagingSenderId: '371597182967',
    projectId: 'shophop-b4133',
    storageBucket: 'shophop-b4133.firebasestorage.app',
    iosBundleId: 'com.example.shopHopApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIuO8liW8d8itUPfyy0VPWgLJXm8TOqfM',
    appId: '1:371597182967:web:13c7ee21eb32150ee350f2',
    messagingSenderId: '371597182967',
    projectId: 'shophop-b4133',
    authDomain: 'shophop-b4133.firebaseapp.com',
    storageBucket: 'shophop-b4133.firebasestorage.app',
    measurementId: 'G-NVTGW92LJY',
  );
}
